### ISSUE TITLE
better prompt engineering

### ISSUE THREAD

**Issue by choccccy** [OoriData/BSW4ClimateCon#15]
the action items and to a lesser extent the summaries are both a lil weak right now. lots of optimization to be done on this front.

also, model selection?

**Comment by choccccy** [comment]
@uogbuji is riffing on the idea of using few shot (potentially from a RAG?) to help improve the action items

**Comment by choccccy** [comment]
@micahtdew throwing you in as an assignee on this one, it's a good chance to get some more experience in LLM stuff, and it should be pretty easy to play with given the current state of the code

**Comment by Aidan-Reese** [comment]
Saturday family unique prompting for the action LLM call.  Slightly different prompt from normal, encouraging larger community/family actions.

**Comment by Aidan-Reese** [comment]
Just made my last commit for this issue, close was a little preemptive.

Last commit was to add one shot examples to the summary step.  

Determined that the model on port 9000 was working better than 8000.

Lastly a regex statement to take out a weird llm ending token "<|im_end|>" that has been showing up after using port 9000.
